### ISSUE TITLE
mysql derived models

### ISSUE THREAD

**Issue by juliuscarvajal** [strongloop/loopback-example-isomorphic#2]
Hey guys, nice work with loopback. Awesome stuff.

I tried to add my own models that are derived from mysql using Arc.
But I am not successful in getting any data out from it.

It would be good if anyone can try to make this work.

Cheers.

I originally tried this on the more complicated example but to no avail:
https://github.com/strongloop/loopback-example-offline-sync/issues/75

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
